name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'requests/**'
      - '*.md'

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.title, '[OPTIC-RELEASE-AUTOMATION]')"
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 22
          - 24
    steps:
      - uses: actions/checkout@v5

      - name: starting postgres...
        run: docker compose -f docker-compose-ci.yml  up -d

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test

      - name: stopping postgres...
        if: always()
        run: docker compose -f docker-compose-ci.yml down -v
